version: "3.8"

services:
  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: .
    environment:
      BROKER_MODE: ${BROKER_MODE:-none}
      SQS_QUEUE_URLS: ${SQS_QUEUE_URLS:-}
      SQS_QUEUE_URL: ${SQS_QUEUE_URL:-}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      MONGO_URL: ${MONGO_URL:-mongodb://mongo:27017}
      MONGO_DB: ${MONGO_DB:-retail_poc}
    depends_on:
      mongo:
        condition: service_healthy
    ports: ["8000:8000"]

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      mongo:
        condition: service_healthy
    ports: ["8081:8081"]